/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-users': CmsUser;
    media: Media;
    locations: Location;
    'cms-posts': CmsPost;
    'webhook-events': WebhookEvent;
    'waitlist-entries': WaitlistEntry;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'cms-posts': CmsPostsSelect<false> | CmsPostsSelect<true>;
    'webhook-events': WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    'waitlist-entries': WaitlistEntriesSelect<false> | WaitlistEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  /**
   * Subdomain slug — e.g. 'vancouver' for vancouver.clothme.io
   */
  slug: string;
  /**
   * Province or state — e.g. BC
   */
  region?: string | null;
  country?: string | null;
  status: 'draft' | 'published' | 'unpublished';
  /**
   * Fill these in before clicking Generate Content. The AI uses them to write city-specific copy.
   */
  aiGeneration?: {
    /**
     * Enter up to 3 boutique names with a one-line description each. One per line. Used by AI to write the Local Shopping section.
     */
    boutiquesContext?: string | null;
    /**
     * Enter article topic ideas, one per line. Used by AI to generate blog articles for this city.
     */
    articleTopics?: string | null;
    /**
     * Set automatically when AI generation runs.
     */
    lastGeneratedAt?: string | null;
  };
  hero?: {
    /**
     * Main headline — should include the city name. Max ~10 words.
     */
    headline?: string | null;
    /**
     * 1–2 sentences expanding on the headline.
     */
    subheadline?: string | null;
    primaryCta?: ('app-store' | 'waitlist') | null;
  };
  painPoints?: {
    headline?: string | null;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  benefits?: {
    headline?: string | null;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  localShopping?: {
    /**
     * e.g. 'Shop Vancouver with confidence'
     */
    headline?: string | null;
    /**
     * 1–2 sentence intro to the boutiques section.
     */
    intro?: string | null;
    boutiques?:
      | {
          name: string;
          neighborhood?: string | null;
          description: string;
          websiteUrl?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    headline?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  aboutPage?: {
    headline?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  contactPage?: {
    headline?: string | null;
    subheadline?: string | null;
  };
  seo?: {
    home?: {
      /**
       * Recommended: 50–60 characters
       */
      metaTitle?: string | null;
      /**
       * Recommended: 140–160 characters
       */
      metaDescription?: string | null;
      ogImage?: (number | null) | Media;
    };
    about?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
    };
    blog?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
    };
    contact?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-posts".
 */
export interface CmsPost {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  location?: (number | null) | Location;
  category?: ('fit-guide' | 'family-shopping' | 'personal-style' | 'location-guide') | null;
  heroImage?: (number | null) | Media;
  /**
   * Image URL received from an auto-blogging webhook. Upload a CMS hero image to replace it.
   */
  externalHeroImageUrl?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * A concise summary for AI search engines and answer engines.
   */
  aiSummary?: string | null;
  source?: {
    provider?: string | null;
    externalId?: string | null;
    publicUrl?: string | null;
    providerCreatedAt?: string | null;
    receivedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: number;
  provider: 'babylovegrowth' | 'outrank';
  eventType?: string | null;
  externalId?: string | null;
  slug?: string | null;
  post?: (number | null) | CmsPost;
  status: 'created' | 'updated' | 'rejected' | 'skipped' | 'error';
  message?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  normalized?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-entries".
 */
export interface WaitlistEntry {
  id: number;
  email: string;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms-users';
        value: number | CmsUser;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'cms-posts';
        value: number | CmsPost;
      } | null)
    | ({
        relationTo: 'webhook-events';
        value: number | WebhookEvent;
      } | null)
    | ({
        relationTo: 'waitlist-entries';
        value: number | WaitlistEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  country?: T;
  status?: T;
  aiGeneration?:
    | T
    | {
        boutiquesContext?: T;
        articleTopics?: T;
        lastGeneratedAt?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        primaryCta?: T;
      };
  painPoints?:
    | T
    | {
        headline?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        headline?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  localShopping?:
    | T
    | {
        headline?: T;
        intro?: T;
        boutiques?:
          | T
          | {
              name?: T;
              neighborhood?: T;
              description?: T;
              websiteUrl?: T;
              image?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        headline?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  aboutPage?:
    | T
    | {
        headline?: T;
        body?: T;
      };
  contactPage?:
    | T
    | {
        headline?: T;
        subheadline?: T;
      };
  seo?:
    | T
    | {
        home?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              ogImage?: T;
            };
        about?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
            };
        blog?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
            };
        contact?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-posts_select".
 */
export interface CmsPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  status?: T;
  publishedAt?: T;
  location?: T;
  category?: T;
  heroImage?: T;
  externalHeroImageUrl?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        ogImage?: T;
      };
  aiSummary?: T;
  source?:
    | T
    | {
        provider?: T;
        externalId?: T;
        publicUrl?: T;
        providerCreatedAt?: T;
        receivedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  eventType?: T;
  externalId?: T;
  slug?: T;
  post?: T;
  status?: T;
  message?: T;
  payload?: T;
  normalized?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-entries_select".
 */
export interface WaitlistEntriesSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'cms-posts';
      value: number | CmsPost;
    } | null;
    global?: string | null;
    user?: (number | null) | CmsUser;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}